
name: Test build on CI 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSVC
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products *
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"

      - name: Build Project with MSBuild
        shell: cmd
        run: |
          msbuild coreassign\CoreAssign.sln /p:Configuration=Release /p:Platform=Arm64

      - name: Run Executable
        run: build\your_executable_name.exe

